name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Check out repository and build project
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      # Run script to generate specific changelog
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python script
        run: python .github/workflows/release.py

      # Publish release to Modrinth and GitHub
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "${{env.NAME}}"
          version: "v${{env.VERSION}}"
          version-type: release
          game-versions: "${{env.MINECRAFT_VERSION}}"
          loaders: fabric
          files: "build/libs/Banners4BM-${{env.VERSION}}.jar"

          # Config for Modrinth
          modrinth-id: rx2aSILw
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
          modrinth-changelog-file: modrinth-changelog.md

          # Config for GitHub
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          github-tag: "v${{env.VERSION}}"
          github-changelog-file: github-changelog.md